name: "Submit Extension"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    name: Build & Submit
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: latest
          run_install: true
      - name: Use Node.js 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
          cache: "pnpm"
      
      - name: Package the extension for Chrome
        run: pnpm build --zip --target=chrome-mv3
      - name: Package the extension for Firefox
        run: pnpm build --zip --target=firefox-mv3

      # https://docs.plasmo.com/framework/workflows/submit
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@c15984c0a74f452851c605cab46f34d9fd6cb158 # v3.8.0
        with:
          keys: ${{ secrets.PLASMO_KEYS }}
          chrome-file: build/chrome-mv3-prod.zip
          firefox-file: build/firefox-mv3-prod.zip
